export const authConstants = {
    SIGNIN_REQUEST: "SIGNIN_REQUEST",
    SIGNIN_FILURE: "SIGNIN_FILURE",
    SIGNIN_SUCCESS: "SIGNIN_SUCCESS",

    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_FILURE: "SIGNUP_FILURE",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",


    UPDATE_REQUEST:"UPDATE_REQUEST",
    UPDATE_FILURE: "UPDATE_FILURE",
    UPDATE_SUCCESS: "UPDATE_SUCCESS",




    SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",

    CATEGORY_SUCCESS: "CATEGORY_SUCCESS",
    CATEGORY_FAILURE: "CATEGORY_FAILURE",


    GETCATEGORY_SUCCESS: "GETCATEGORY_SUCCESS",
    GETCATEGORY_FAILURE: "GETCATEGORY_FAILURE",


    UPDATECATEGORY_SUCCESS: "UPDATECATEGORY_SUCCESS",
    UPDATECATEGORY_FAILURE: "UPDATECATEGORY_FAILURE",

    DELETE_SUCCESS: "DELETE_SUCCESS",
    DELETE_FAILURE: "DELETE_FAILURE",

    
    PRODUCT_SUCCESS: "PRODUCT_SUCCESS",
    PRODUCT_FAILURE: "PRODUCT_FAILURE",

       
    GETPRODUCT_SUCCESS: "GETPRODUCT_SUCCESS",
    GETPRODUCT_FAILURE: "GETPRODUCT_FAILURE",

    UPDATEPRODUCT_SUCCESS:"UPDATEPRODUCT_SUCCESS",
    UPDATEPRODUCT_FAILURE:"UPDATEPRODUCT_FAILURE",

    DELETEPRODUCT_SUCCESS:"DELETEPRODUCT_SUCCESS",
    DELETEPRODUCT_FAILURE:"DELETEPRODUCT_FAILURE",

}